# docker-compose.yml
version: '2'

services:
  graphql:
    build: ./golang
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://graphql:8080/graphql?query=%7B__typename%7D" ]
    #   timeout: 20s
    #   interval: 10s
    #   retries: 3
    env_file:
      - environment.env
    ports:
     - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 20s
      interval: 10s
      retries: 3
    restart: always
    env_file:
      - environment.env
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgres/db:/docker-entrypoint-initdb.d/