# docker-compose.yml
version: '2'

services:
  graphql:
    build: ./golang
    env_file:
      - environment.env
    ports:
     - "8080:8080"
    depends_on:
      - "db"

  db:
    build: ./postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    env_file:
      - environment.env
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgres/db:/docker-entrypoint-initdb.d/