// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
